apiVersion: v1
kind: Service
metadata:
  name: cloudify-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: cloudify-service
  ports:
    - protocol: TCP
      port: 80        # Public port
      targetPort: 8080 # Container port
