apiVersion: v1
kind: Service
metadata:
  name: cloudify-service
  namespace: cloudify-namespace
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_Cloudify_CloudifyCluster_italynorth
    service.beta.kubernetes.io/azure-load-balancer-ip-address: 72.146.64.150
spec:
  type: LoadBalancer
  selector:
    app: cloudify-service
  ports:
    - protocol: TCP
      port: 80        # Public port
      targetPort: 8080 # Container port
