kumuluz.ee.openapi:
  enabled: true
  ui:
    enabled: true  # Ovdje omogućavate Swagger UI
  title: "My API"
  version: "v1"
  description: "API documentation"
  contact:
    name: "John Doe"
    email: "johndoe@example.com"
