kumuluzee:
  name: Cloudify
  version: 1.0.0
  env:
    name: dev
#  datasources:
#    - jndi-name: jdbc/CloudifyDS
#      connection-url: jdbc:postgresql://localhost:5432/cloudifydb
#      username: cloudify_user
#      password: secure_password
#      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CloudifyDS
  rest-client:
    registrations:
      - class: api-service
        url: http://localhost:8082/v1
        read-timeout: 5000
integrations:
  external-api:
    base-url: http://localhost:8082/v1
