kumuluzee:
  name: Cloudify
  version: 1.0.0
  env:
    name: dev
#  datasources:
#    - jndi-name: jdbc/CloudifyDS
#      connection-url: jdbc:postgresql://localhost:5432/cloudifydb
#      username: cloudify_user
#      password: secure_password
#      max-pool-size: 20
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CloudifyDS
  rest-client:
    registrations:
      - class: api-service
        url: http://localhost:8082/v1
        read-timeout: 5000

  openapi-mp:
    enabled: true
    info:
      title: "Swagger !Cloudify - OpenAPI 3.0"
      description: "Description of your project"
      version: "1.0.11"
    servers:
      - url: "http://localhost:8080/v1"
    tags:
      - name: "Flight Booking Service"
        description: "Everything about your booking"
    openapi-mp-ui:
      enabled: true
      path: "/swagger-ui"
      title: "API Documentation"
      filter: true