kumuluzee:
  name: Cloudify
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: cloudify
      connection-url: jdbc:postgresql://localhost:5432/cloudify
      username: cloudify
      password: password
      database: cloudify
      max-pool-size: 20
  logging:
    levels:
      com.kumuluz: DEBUG
      javax.sql: DEBUG
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/cloudify
  rest-client:
    registrations:
      - class: api-service
        url: http://localhost:8082/v1
        read-timeout: 5000

  openapi-mp:
    enabled: true
    info:
      title: "Swagger !Cloudify - OpenAPI 3.0"
      description: "Description of your project"
      version: "1.0.11"
    servers:
      - url: "http://localhost:8080/v1"
    tags:
      - name: "Flight Booking Service"
        description: "Everything about your booking"
    openapi-mp-ui:
      enabled: true
      path: "/swagger-ui"
      title: "API Documentation"
      filter: true